/*
 * This class is responsible for generating all of the code for the action panel
 * in the GUI
 */

package simse.codegenerator.guigenerator;

import simse.modelbuilder.objectbuilder.Attribute;
import simse.modelbuilder.objectbuilder.DefinedObjectTypes;
import simse.modelbuilder.objectbuilder.SimSEObjectType;
import simse.modelbuilder.objectbuilder.SimSEObjectTypeTypes;
import simse.modelbuilder.actionbuilder.DefinedActionTypes;
import simse.codegenerator.CodeGenerator;
import simse.codegenerator.CodeGeneratorConstants;
import simse.codegenerator.CodeGeneratorUtils;

import java.util.ArrayList;
import java.util.Vector;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.lang.model.element.Modifier;
import javax.swing.JOptionPane;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

public class ArtifactsPanelGenerator implements CodeGeneratorConstants {
  private DefinedObjectTypes objTypes; // holds all of the defined object types
                                       // from an sso file
  private DefinedActionTypes actTypes; // holds all of the defined action types
                                       // from an ssa file
  private File directory; // directory to save generated code into
  
  private ArrayList<String> impTypes;
  
  private ArrayList<String> impActions;

  public ArtifactsPanelGenerator(DefinedObjectTypes objTypes, 
  		DefinedActionTypes actTypes, File directory) {
    this.objTypes = objTypes;
    this.actTypes = actTypes;
    this.directory = directory;
    this.impTypes = new ArrayList<>();
    this.impActions = new ArrayList<>();
  }

  public void generate() {
    File actPanelFile = new File(directory, ("simse\\gui\\ArtifactsPanel.java"));
    if (actPanelFile.exists()) {
      actPanelFile.delete(); // delete old version of file
    }
    try {
      FileWriter writer = new FileWriter(actPanelFile);
      writer
          .write("/* File generated by: simse.codegenerator.guigenerator.ArtifactsPanelGenerator */");
      ClassName enumeration = ClassName.get("java.util", "Enumeration");
      ClassName hashtable = ClassName.get("java.util", "Hashtable");
      ClassName vector = ClassName.get("java.util", "Vector");
      ClassName eventhandler = ClassName.get("javafx.event", "EventHandler");
      ClassName pos = ClassName.get("javafx.geometry", "Pos");
      ClassName label = ClassName.get("javafx.scene.control", "Label");
      ClassName scrollpane = ClassName.get("javafx.scene.control", "ScrollPane");
      ClassName titledpane = ClassName.get("javafx.scene.control", "TitledPane");
      ClassName imageview = ClassName.get("javafx.scene.image", "ImageView");
      ClassName mousebutton = ClassName.get("javafx.scene.input", "MouseButton");
      ClassName mouseevent = ClassName.get("javafx.scene.input", "MouseEvent");
      ClassName border = ClassName.get("javafx.scene.layout", "Border");
      ClassName borderstroke = ClassName.get("javafx.scene.layout", "BorderStroke");
      ClassName borderstrokestyle = ClassName.get("javafx.scene.layout", "BorderStrokeStyle");
      ClassName borderwidths = ClassName.get("javafx.scene.layout", "BorderWidths");
      ClassName cornerradii = ClassName.get("javafx.scene.layout", "CornerRadii");
      ClassName gridpane = ClassName.get("javafx.scene.layout", "GridPane");
      ClassName hbox = ClassName.get("javafx.scene.layout", "HBox");
      ClassName pane = ClassName.get("javafx.scene.layout", "Pane");
      ClassName vbox = ClassName.get("javafx.scene.layout", "VBox");
      ClassName color = ClassName.get("javafx.scene.paint", "Color");
      ClassName font = ClassName.get("javafx.scene.text", "Font");
      ClassName artifact = ClassName.get("simse.adts.objects", "Artifact");
      ClassName javafxhelpers = ClassName.get("simse.gui.util", "JavaFXHelpers");
      ClassName logic = ClassName.get("simse.logic", "Logic");
      ClassName state = ClassName.get("simse.state", "State");
      ClassName simsegui = ClassName.get("simse.gui", "SimSEGUI");
      ClassName panels = ClassName.get("simse.gui", "Panels");
      ClassName simsepanel = ClassName.get("simse.gui", "SimSEPanel");
      ClassName tabpanel = ClassName.get("simse.gui", "TabPanel");
      TypeName vOfA = ParameterizedTypeName.get(vector, artifact);
      TypeName hashArtVB = ParameterizedTypeName.get(hashtable, artifact, vbox);
      TypeName hashArtHB = ParameterizedTypeName.get(hashtable, artifact, hbox);
      TypeName hashArtLab = ParameterizedTypeName.get(hashtable, artifact, label);
      TypeName enumOfE = ParameterizedTypeName.get(enumeration, artifact);
      TypeName mouseHandler = ParameterizedTypeName.get(eventhandler, mouseevent);
      // constructor:
      MethodSpec constructor = MethodSpec.constructorBuilder()
    		  .addModifiers(Modifier.PUBLIC)
    		  .addParameter(simsegui, "gui")
    		  .addParameter(state, "s")
    		  .addParameter(logic, "l")
    		  .addStatement("$N = s", "state")
    		  .addStatement("$N = l", "logic")
    		  .addStatement("$N = gui", "mainGUIFrame")
    		  .addStatement("$N = new $T()", "layout", vbox)
    		  .addStatement("$N.setId(\"actionPanelVBox\")", "layout")
    		  .addStatement("$N = new $T()", "artifactPane", scrollpane)
    		  .addStatement("$N.setId(\"scrollPaneActionPanel\")", "artifactPane")
    		  .addStatement("$N.setPrefSize(225, 425)", "artifactPane")
    		  .addStatement("$N.setId(\"ActionPanelMain\")", "artifactPane")
    		  .addStatement("artsToArtPanels = new $T()", hashArtVB)
    		  .addStatement("artsToPicPanels = new $T()", hashArtHB)
    		  .addStatement("artsToPicLabels = new $T()", hashArtLab)
    		  .addStatement("artsToKeyLabels = new $T()", hashArtLab)
    		  .addStatement("$T titlePanel = new $T(\"$T Panel\", $N)", titledpane, titledpane, artifact, "artifactPane")
    		  .addStatement("titlePanel.set$T(Border.EMPTY)", border)
    		  .addStatement("titlePanel.setId(\"ActionTitlePanel\")")
    		  .addStatement("titlePanel.setBackground($T.createBackground$T(Color.rgb(102, 102, 102, 1)))", javafxhelpers, color)
    		  .addStatement("$N.getChildren().add(titlePanel)", "layout")
    		  .addStatement("update()")
    		  .addStatement("this.getChildren().add(layout)")
    		  .build();

      // update function:
      MethodSpec update = MethodSpec.methodBuilder("update")
    		  .addModifiers(Modifier.PUBLIC)
    		  .returns(void.class)
    		  .addStatement("$N.setContent(null)", "artifactPane")
    		  .addStatement("artsToArtPanels.clear()")
    		  .addStatement("$T titleLabel = new $T(\"Current Activities:\")", label, label)
    		  .addStatement("$T f = titleLabel.getFont()", font)
    		  .addStatement("$T newFont = new $T(f.getName(), 15)", font, font)
    		  .addStatement("titleLabel.setFont(newFont)")
    		  .addStatement("titleLabel.setTextFill($T.BLACK)", color)
    		  .addStatement("$T artifacts = new $T()", vbox, vbox)
    		  .addStatement("artifacts.getChildren().add(titleLabel)")
    		  .addStatement("artifacts.setSpacing(2)")
    		  .addStatement("$T allArts = $N.getArtifactStateRepository().getAll()", vOfA, "state")
    		  .beginControlFlow("for (int i = 0; i < allArts.size(); i++)")
    		  .addStatement("$T art = allArts.elementAt(i)", artifact)
    		  .addCode(continueIfHire())
    		  .beginControlFlow("if (artsToArtPanels.get(art) == null)")
    		  .addStatement("$T tempPanel = new $T()", vbox, vbox)
    		  .addStatement("tempPanel.addEventHandler($T.ANY, this)", mouseevent)
    		  .addStatement("artsToArtPanels.put(art, tempPanel)")
    		  .endControlFlow()
    		  .beginControlFlow("if (artsToPicPanels.get(art) == null)")
    		  .addStatement("$T tempPanel = new $T()", hbox, hbox)
    		  .addStatement("tempPanel.addEventHandler($T.ANY, this)", mouseevent)
    		  .addStatement("artsToPicPanels.put(art, tempPanel)")
    		  .endControlFlow()
    		  .addStatement("$T artPanel = artsToArtPanels.get(art)", vbox)
    		  .addStatement("artPanel.getChildren().removeAll()")
    		  .addStatement("$T picPanel = ($T) artsToPicPanels.get(art)", hbox, hbox)
    		  .addStatement("picPanel.setSpacing(5)")
    		  .addStatement("picPanel.setAlignment($T.BASELINE_LEFT)", pos)
    		  .addStatement("picPanel.getChildren().removeAll()")
    		  .addStatement("$T gpLayout = new $T()", gridpane, gridpane)
    		  .addStatement("gpLayout.getChildren().add(artPanel)")
    		  .addStatement("artPanel.setId(\"ActionPanelArtifact\")")
    		  .addStatement("picPanel.setId(\"ActionPanelArtifactBox\")")
    		  .addStatement("picPanel.prefWidthProperty().bind($N.widthProperty())", "artifactPane")
    		  .addStatement("artPanel.prefWidthProperty().bind($N.widthProperty())", "artifactPane")
    		  .beginControlFlow("if (artsToPicLabels.get(art) == null)")
    		  .addStatement("$T ico = $T.createImageView($T.getImage(art))", imageview, javafxhelpers, tabpanel)
    		  .beginControlFlow("if(ico != null)")
    		  .addStatement("ico.setFitHeight(40)")
    		  .addStatement("ico.setFitWidth(40)")
    		  .addStatement("$T temp = new $T()", label, label)
    		  .addStatement("temp.setGraphic(ico)")
    		  .addStatement("temp.addEventHandler($T.ANY, this)", mouseevent)
    		  .addStatement("artsToPicLabels.put(art, temp)")
    		  .endControlFlow()
    		  .endControlFlow()
    		  .addStatement("$T picLabel = artsToPicLabels.get(art)", label)
    		  .beginControlFlow("if (picLabel != null)")
    		  .addStatement("picLabel.setAlignment($T.BASELINE_LEFT)", pos)
    		  .addStatement("picLabel.setId(\"ArtifactPic\")")
    		  .beginControlFlow("if(!picPanel.getChildren().contains(picLabel))")
    		  .addStatement("picPanel.getChildren().add(picLabel)")
    		  .endControlFlow()
    		  .endControlFlow()
    		  .addCode(getArtifactTypes())
    		  .addStatement("picPanel.setBorder(Border.EMPTY)")
    		  .beginControlFlow("if(!artPanel.getChildren().contains(picPanel))")
    		  .addStatement("artPanel.getChildren().add(picPanel)")
    		  .endControlFlow()
    		  .addStatement("artPanel.set$T(new Border(new $T($T.rgb(102, 102, 102, 1), $T.SOLID, $T.EMPTY, $T.FULL)))", border, borderstroke, color, borderstrokestyle, cornerradii, borderwidths)
    		  .addStatement("artPanel.setBorder(new $T(new $T($T.BLACK,\n"
    		  		+ "$T.SOLID,\n"
    		  		+ "$T.EMPTY, $T.THIN)))", border, borderstroke, color, borderstrokestyle, cornerradii, borderstroke)
    		  .addStatement("artifacts.getChildren().add(artPanel)")
    		  .endControlFlow()
    		  .addStatement("$N.setContent(artifacts)", "artifactPane")
    		  .build();	

      MethodSpec artFromLabel = MethodSpec.methodBuilder("getArtFromPicLabel")
    		  .addModifiers(Modifier.PRIVATE)
    		  .returns(artifact)
    		  .addParameter(label, "label")
    		  .beginControlFlow("for ($T keys = artsToPicLabels.keys(); keys.hasMoreElements();)", enumOfE)
    		  .addStatement("$T keyArt = keys.nextElement()", artifact)
    		  .beginControlFlow("if (artsToPicLabels.get(keyArt) == label)")
    		  .addStatement("return keyArt")
    		  .endControlFlow()
    		  .endControlFlow()
    		  .addStatement("return null")
    		  .build();
      
      
      MethodSpec artFromPanel = MethodSpec.methodBuilder("getArtFromPanel")
    		  .addModifiers(Modifier.PRIVATE)
    		  .returns(artifact)
    		  .addParameter(pane, "panel")
    		  .beginControlFlow("for ($T keys = artsToArtPanels.keys(); keys.hasMoreElements();)", enumOfE)
    		  .addStatement("$T keyArt = keys.nextElement()", artifact)
    		  .beginControlFlow("if (artsToArtPanels.get(keyArt) == panel)")
    		  .addStatement("return keyArt")
    		  .endControlFlow()
    		  .endControlFlow()
    		  .beginControlFlow("for ($T keys = artsToPicPanels.keys(); keys.hasMoreElements();)", enumOfE)
    		  .addStatement("$T keyArt = keys.nextElement()", artifact)
    		  .beginControlFlow("if (artsToArtPanels.get(keyArt) == panel)")
    		  .addStatement("return keyArt")
    		  .endControlFlow()
    		  .endControlFlow()
    		  .addStatement("return null")
    		  .build();
      
      MethodSpec handle = MethodSpec.methodBuilder("handle")
    		  .addAnnotation(Override.class)
    		  .addModifiers(Modifier.PUBLIC)
    		  .returns(void.class)
    		  .addParameter(mouseevent, "event")
    		  .beginControlFlow("if (event.getEventType() == $T.MOUSE_RELEASED)", mouseevent)
    		  .beginControlFlow("if (event.getSource() instanceof $T)", label)
    		  .addStatement("$T label = ($T) event.getSource()", label, label)
    		  .addStatement("$T art = getArtFromPicLabel(label)", artifact)
    		  .beginControlFlow("if (art != null)")
    		  .beginControlFlow("if (event.getButton().equals($T.PRIMARY))", mousebutton)
    		  .addStatement("$N.getTabPanel().setGUIChanged()", "mainGUIFrame")
    		  .addStatement("$N.getTabPanel().setObjectInFocus(art)", "mainGUIFrame")
    		  .addStatement("$N.getAttributePanel().setGUIChanged()", "mainGUIFrame")
    		  .addStatement("$N.getAttributePanel().setObjectInFocus(art, $T.createImage(TabPanel.getImage(art)))", "mainGUIFrame", javafxhelpers)
    		  .endControlFlow()
    		  .endControlFlow()
    		  .nextControlFlow("else if (event.getSource() instanceof $T)", pane)
    		  .addStatement("$T pane = ($T) event.getSource()", pane, pane)
    		  .addStatement("$T art = getArtFromPanel(pane)", artifact)
    		  .beginControlFlow("if (art != null)")
    		  .beginControlFlow("if (event.getButton().equals($T.PRIMARY))", mousebutton)
    		  .addStatement("$N.getTabPanel().setGUIChanged()", "mainGUIFrame")
    		  .addStatement("$N.getTabPanel().setObjectInFocus(art)", "mainGUIFrame")
    		  .addStatement("$N.getAttributePanel().setGUIChanged()", "mainGUIFrame")
    		  .addStatement("$N.getAttributePanel().setObjectInFocus(art,JavaFXHelpers.createImage(TabPanel.getImage(art)))", "mainGUIFrame")
    		  .endControlFlow()
    		  .endControlFlow()
    		  .endControlFlow()
    		  .endControlFlow()
    		  .build();
      
      MethodSpec getPanelType = MethodSpec.methodBuilder("getPanelType")
    		  .addAnnotation(Override.class)
    		  .addModifiers(Modifier.PUBLIC)
    		  .returns(panels)
    		  .addStatement("return $T.ARTIFACTS", panels)
    		  .build();
      
      TypeSpec actionPanel = TypeSpec.classBuilder("ArtifactsPanel")
    		  .addModifiers(Modifier.PUBLIC)
    		  .superclass(pane)
    		  .addSuperinterface(mouseHandler)
    		  .addSuperinterface(simsepanel)
    		  .addField(state, "state", Modifier.PRIVATE)
    		  .addField(logic, "logic", Modifier.PRIVATE)
    		  .addField(simsegui, "mainGUIFrame", Modifier.PRIVATE)
    		  .addField(artifact, "selectedArt", Modifier.PRIVATE)
    		  .addField(scrollpane, "artifactPane", Modifier.PRIVATE)
    		  .addField(hashArtVB, "artsToArtPanels", Modifier.PRIVATE)
    		  .addField(hashArtHB, "artsToPicPanels", Modifier.PRIVATE)
    		  .addField(hashArtLab, "artsToPicLabels", Modifier.PRIVATE)
    		  .addField(hashArtLab, "artsToKeyLabels", Modifier.PRIVATE)
    		  .addField(vbox, "layout", Modifier.PRIVATE)
    		  .addMethod(constructor)
    		  .addMethod(update)
    		  .addMethod(artFromLabel)
    		  .addMethod(artFromPanel)
    		  .addMethod(handle)
    		  .addMethod(getPanelType)
    		  .build();
      
      JavaFile file = JavaFile.builder("", actionPanel)
    		  .build();
      
      String fileString = "package simse.gui;\n\nimport javafx.scene.text.TextAlignment;\n";
      for (String type : impTypes) {
			fileString = fileString + "import simse.adts.objects." + type + ";\n";
		}
      
      for (String actionI : impActions) {
    	  fileString = fileString + "import simse.adts.actions." + actionI +"Action;\n";
      }
		
		fileString = fileString + file.toString();
		
		
		writer.write(fileString);
      
      writer.close();
    } catch (IOException e) {
      JOptionPane.showMessageDialog(null, ("Error writing file "
          + actPanelFile.getPath() + ": " + e.toString()), "File IO Error",
          JOptionPane.WARNING_MESSAGE);
    }
  }
  
  private String continueIfHire() {
	  String hire = "";
	  if (CodeGenerator.allowHireFire) {
		  hire = hire.concat("if (!art.getHired())\n");
		  hire = hire.concat("continue;\n");
	      }
	  return hire;
  }
  
  private String getArtifactTypes() {
	  String arts = "";
	  Vector<SimSEObjectType> artTypes = objTypes
	            .getAllObjectTypesOfType(SimSEObjectTypeTypes.ARTIFACT);
	        for (int i = 0; i < artTypes.size(); i++) {
	          SimSEObjectType tempType = artTypes.elementAt(i);
	          if (!this.impTypes.contains(CodeGeneratorUtils.getUpperCaseLeading(tempType.getName()))) {
	        	  this.impTypes.add(CodeGeneratorUtils.getUpperCaseLeading(tempType.getName()));
	          }
	          if (i > 0) {
	        	  arts = arts.concat("else ");
	          }

	          Vector<Attribute> v = tempType.getAllAttributes();
	          Attribute keyAtt = null;
	          for (Attribute att : v) {
	            if (att.isKey())
	              keyAtt = att;
	          }

	          arts = arts.concat("if(art instanceof "
	              + CodeGeneratorUtils.getUpperCaseLeading(tempType.getName()) + ")");
	          arts = arts.concat("\n");
	          arts = arts.concat("{");
	          arts = arts.concat("\n");
	          arts = arts.concat(CodeGeneratorUtils.getUpperCaseLeading(tempType.getName()) 
	          		+ " e = (" + 
	          		CodeGeneratorUtils.getUpperCaseLeading(tempType.getName()) + 
	          		")art;");
	          arts = arts.concat("\n");
	          arts = arts.concat("if(artsToKeyLabels.get(e) == null)");
	          arts = arts.concat("\n");
	          arts = arts.concat("{");
	          arts = arts.concat("\n");
	          arts = arts.concat("Label temp = new Label(\"\" + e.get"
	              + CodeGeneratorUtils.getUpperCaseLeading(keyAtt.getName()) + 
	              "());");
	          arts = arts.concat("\n");
	          arts = arts.concat("temp.setTextFill(Color.BLACK);");
	          arts = arts.concat("\n");
	          arts = arts.concat("temp.setAlignment(Pos.BASELINE_LEFT);");
	          arts = arts.concat("\n");
	          arts = arts.concat("temp.setTextAlignment(TextAlignment.LEFT);");
	          arts = arts.concat("\n");
	          arts = arts.concat("artsToKeyLabels.put(e, temp);");
	          arts = arts.concat("\n");
	          arts = arts.concat("}");
	          arts = arts.concat("\n");
	          arts = arts.concat("Label keyLabel = artsToKeyLabels.get(e);");
	          arts = arts.concat("\n");
	          arts = arts.concat("keyLabel.setId(\"ArtifactName\");");
	          arts = arts.concat("\n");
	          arts = arts.concat("if(!picPanel.getChildren().contains(keyLabel))");
	          arts = arts.concat("{");
	          arts = arts.concat("\n");
	          arts = arts.concat("picPanel.getChildren().add(keyLabel);");
	          arts = arts.concat("\n");
	          arts = arts.concat("}");
	          arts = arts.concat("\n");
	          arts = arts.concat("}");
	          arts = arts.concat("\n");
	        }
	  return arts;
  }
}